
import os

#variabel
print( "[==========================================]")
print( "          WELCOME IN MY CHANNEL"          )
print( " Create By : Mr.WijayaHacks_Load404")
print( " Wa.Me     : 082131764311")
print( " RECODE IJIN DULU COKK!!")
print( "[==========================================]")

print 
print 

#input output
os.system("sleep 3")
os.system("clear")
uss = input("Masukkan Username= ")
if(uss == "Wijaya" ):
	print("Tunggu Sebentar")
	os.system("sleep 1")
else:
	print("Username Tidak Terdaftar")
	os.system("Sleep 1")
	os.system("python ScT00LsV1.py")
pwd = input("Masukkan Password= ")
if(pwd == "GansV1"):
	os.system("sleep 3")
	print("login sukses")
	os.system("sleep 1")
	print("tunggu sebentar")
	os.system("clear")
else:
	print("password salah")
	os.system("sleep 1")
	os.system("python ScT00LsV1.py")
	
print("Loading(#.........)|5%| |")
os.system("sleep 2")
os.system("clear")
print("Loading(#.........)|5%| -")
os.system("sleep 1")
os.system("clear")
print("Loading(#.........)|5%| |")
os.system("sleep 0.5")
os.system("clear")
print("Loading(#.........)|5%| -")
os.system("sleep 4")
os.system("clear")
print("Loading(#.........)|10%| |")
os.system("sleep 1")
os.system("clear")
print("Loading(#.........)|10%| -")
os.system("sleep 0.5")
os.system("clear")
print("Loading(#.........)|10%|")
os.system("sleep 4")
os.system("clear")
print("Loading(#.........)|15%|")
os.system("sleep 3")
os.system("clear")
print("Loading(##........)|20%|")
os.system("sleep 2")
os.system("clear")
print("Loading(##........)|25%|")
os.system("sleep 1")
os.system("clear")
print("Loading(###.......)|30%|")
os.system("sleep 1")
os.system("clear")
print("Loading(###.......)|35%|")
os.system("sleep 0.5")
os.system("clear")
print("Loading(####......)|40%|")
os.system("sleep 0.5")
os.system("clear")
print("Loading(####......)|45%|")
os.system("sleep 0.5")
os.system("clear")
print("Loading(#####.....)|50%|")
os.system("sleep 0.5")
os.system("clear")
print("Loading(#####.....)|55%|")
os.system("sleep 0.5")
os.system("clear")
print("Loading(######....)|60%|")
os.system("sleep 0.5")
os.system("clear")
print("Loading(######....)|65%|")
os.system("sleep 1")
os.system("clear")
print("Loading(#######...)|70%|")
os.system("sleep 2")
os.system("clear")
print("Loading(#######...)|75%|")
os.system("sleep 0.5")
os.system("clear")
print("Loading(########..)|80%|")
os.system("sleep 0.5")
os.system("clear")
print("Loading(########..)|85%|")
os.system("sleep 0.5")
os.system("clear")
print("Loading(#########.)|90%|")
os.system("sleep 0.5")
os.system("clear")
print("Loading(#########.)|95%|")
os.system("sleep 0.5")
os.system("clear")
print("Loading(##########)|100%|")
os.system("sleep 3")
os.system("clear")


#input output1
os.system("sleep 1")
print("[==========================================]")
os.system("sleep 1")
print("[            WELCOME IN SCT00LS            ]")
os.system("sleep 1")
print("[==========================================]")
os.system("sleep 1")
print("[ Create By : Mr.WijayaHacks_Load404       ]")
print("[ Wa.Me     : 082131764311                 ]")
print("[ RECODE IJIN DULU COKK!!                  ]")
os.system("sleep 1")
print("[==========================================]")
print("[ SCT00LS======               ======ST00LS ]")
print("[            ======SCT00LS======           ]")
print("[ SCT00LS======               ======SCOOLS ]")
print("[==========================================]")
print("")
print("[==========================================]")
os.system("sleep 1")
print(" [1] INSTALL TERMUX-THEME")
print("[==========================================]")
os.system("sleep 1")
print(" [2] INSTALL VIRTEX")
print("[==========================================]")
os.system("sleep 1")
print(" [3] INSTALL DDOS TORSHAMMER")
print("[==========================================]")
os.system("sleep 1")
print(" [4] INSTALL NMAP")
print("[==========================================]")
os.system("sleep 1")
print(" [5] INSTALL LAZYMUX")
print("[==========================================]")
os.system("sleep 1")
print(" [0] EXIT")
print("[==========================================]")
os.system("sleep 1")
input = input("Masukkan Pilihan Anda : ")
os.system("sleep 1")
print("[==========================================]")
if(input == "1"):
	os.system("clear")
	print("INSTALL TERMUX-THEME")
	os.system("sleep 3")
	os.system("cd $HOME")
	os.system("apt update && apt upgrade")
	os.system("apt install python2")
	os.system("apt install git")
	os.system("git clone https://github.com/saydog/termux-theme")
	print("INSTALLING SUCCESS")
elif(input == "2"):
	os.system("clear")
	print("INSTALL VIRTEX")
	os.system("sleep 3")
	os.system("cd $HOME")
	os.system("apt update && apt upgrade")
	os.system("pkg install git")
	os.system("pkg install curl")
	os.system("pkg install figlet")
	os.system("pkg install ruby")
	os.system("gem install lolcat")
	os.system("git clone https://github.com/muhammadfathul/VIRTEX")
	print("INSTALLING SUCCESS")
elif(input == "3"):
	os.system("clear")
	print("INSTALL DDOS TORSHAMMER")
	os.system("sleep 3")
	os.system("clear")
	os.system("cd $HOME")
	os.system("apt update && apt upgrade")
	os.system("apt install git")
	os.system("apt install tor")
	os.system("apt install python2")
	os.system("git clone https://github.com/dotfighter/torshammer.git")
	print("INSTALLING SUCCES")
elif(input == "4"):
	os.system("clear")
	print("INSTALL NMAP")
	os.system("sleep 3")
	os.system("cd $HOME")
	os.system("apt update && apt upgrade")
	os.system("pkg install nmap")
	print("INSTALLING SUCCES")
elif(input == "5"):
	os.system("clear")
	print("INSTALL LAZYMUX")
	os.system("sleep 3")
	os.system("cd $HOME")
	os.system("apt update && apt upgrade")
	os.system("apt install python2")
	os.system("apt python2-dev")
	os.system("apt install git")
	os.system("git clone https://github.com/Gameye98/lazymux.git")
	print("INSTALLING SUCCES")
elif(input == "0"):
	os.system("clear")
	print("Terima Kasih Telah Menggunakan Tools Kami")
	os.system("sleep 1")
	print("See You")
	os.system("sleep 3")
	os.system("cd $HOME")
else:
	os.system("clear")
	print("PILIHAM TIDAK ADA")
	print("ULANG DARI AWAL")
	os.system("sleep 2")
	os.system("python new.py")